
export const TODO_LIST_REQUEST = "TODO_LIST_REQUEST";
export const TODO_LIST_SUCCESS = "TODO_LIST_SUCCESS";
export const TODO_LIST_FAIL = "TODO_LIST_FAIL";
export const TODO_ADD_ITEM = "TODO_ADD_ITEM";
export const TODO_REMOVE_ITEM = "TODO_REMOVE_ITEM";
export const TODO_COMPLETE_TODO = "TODO_COMPLETE_TODO";